services:
  postgres:
    image: postgres:16.2
    container_name: postgres-container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: restaurant
    ports:
      - "5432:5432"
  
  nest:
    build:
      context: .
      dockerfile: docker
    container_name: zag-assessment-restaurant
    depends_on:
      - postgres
    ports:
      - "3000:3000"
    environment:
      DB_NAME: restaurant
      DB_USERNAME: postgres
      DB_PASSWORD: root
      DB_HOST: postgres
      DB_PORT: 5432